# Wi-Fi credentials
deye-lite_wifi_ssid: "YOUR_WIFI_SSID"
deye-lite_wifi_password: "YOUR_WIFI_PASSWORD"

# Home Assistant API encryption key
deye-lite_api_encryption_key: "YOUR_ENCRYPTION_KEY"

# Password for OTA firmware updates
deye-lite_ota_password: "YOUR_OTA_PASSWORD"

# Fallback hotspot password (used when the module cannot connect to Wi-Fi)
deye-lite_hotspot_pass: "YOUR_HOTSPOT_PASSWORD"

# Username and password for the built-in web interface
deye-lite_web_user: "YOUR_WEB_USERNAME"
deye-lite_web_password: "YOUR_WEB_PASSWORD"
